name: build

on:
  push:
    branches:
    - feature/*
    - bug/*

jobs:
  build:

    name: build
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@master

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.300'
    
    - name: 'Perform build'
      shell: bash
      run: |
        dotnet build --configuration Release --output ./output
