name: build

on:
  push:
    branches:
    - feature/*
    - bug/*

jobs:
  build:

    name: build
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@master

    - name: Run a one-line script
      run: echo Hello, world!
    