name: build

on:
  push:
    branches:
    - feature/*
    - bug/*

jobs:
  build:

    name: build
    runs-on: windows-latest

    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@master

    - name: login to azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: setup .net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.300'
    
    - name: perform build
      shell: pwsh
      run: |
        dotnet build --configuration Release --output ./output

    - name: deploy azure functions
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: azure-durable-functions-fa
        package: './output'
