name: release

on:
  push:
    branches:
    - master
    - bug/*

jobs:
  release:

    name: release
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@master

    - name: login to azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: setup .net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.300'
    
    - name: perform build
      shell: bash
      run: |
        dotnet build --configuration Release --output ./output

    - name: deploy azure functions
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: azure-durable-functions-fa